# Generated by Django 6.0.1 on 2026-02-11 00:41

import api.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Share Token')),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Password Hash')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('max_downloads', models.IntegerField(default=0, verbose_name='Max Downloads (0 for unlimited)')),
                ('current_downloads', models.IntegerField(default=0, verbose_name='Current Downloads')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Share Link',
                'verbose_name_plural': 'Share Links',
            },
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at'], 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='storagecredential',
            options={'ordering': ['-created_at'], 'verbose_name': 'Storage Credential', 'verbose_name_plural': 'Storage Credentials'},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='prefix',
            field=models.CharField(default='', editable=False, max_length=10, verbose_name='Key Prefix'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='scopes',
            field=models.JSONField(blank=True, default=list, verbose_name='Scopes/Permissions'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='api.category'),
        ),
        migrations.AddField(
            model_name='file',
            name='download_count',
            field=models.IntegerField(default=0, verbose_name='Download Count'),
        ),
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(blank=True, max_length=20, verbose_name='File Extension'),
        ),
        migrations.AddField(
            model_name='file',
            name='folder_path',
            field=models.CharField(default='/', max_length=255, verbose_name='Virtual Folder Path'),
        ),
        migrations.AddField(
            model_name='file',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Is Favorite'),
        ),
        migrations.AddField(
            model_name='file',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is Public'),
        ),
        migrations.AddField(
            model_name='file',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Accessed'),
        ),
        migrations.AddField(
            model_name='file',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Original Filename'),
        ),
        migrations.AddField(
            model_name='file',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Thumbnail URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='User Preferences'),
        ),
        migrations.AddField(
            model_name='storagecredential',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bucket Name'),
        ),
        migrations.AddField(
            model_name='storagecredential',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default'),
        ),
        migrations.AddField(
            model_name='storagecredential',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('upload', 'File Upload'), ('delete', 'File Delete'), ('update', 'File Update'), ('create_category', 'Category Created'), ('api_key_generated', 'API Key Generated'), ('settings_update', 'Settings Updated'), ('other', 'Other Action')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(editable=False, max_length=255, unique=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Used At'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Key Name'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7, validators=[api.models.validate_hex_color], verbose_name='Color Label'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='folder', max_length=50, verbose_name='Icon Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='file',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='files', to='api.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(max_length=255, verbose_name='Provider File ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=100, verbose_name='MIME Type'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=255, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(validators=[api.models.validate_file_size], verbose_name='Size (Bytes)'),
        ),
        migrations.AlterField(
            model_name='file',
            name='storage_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='api.storagecredential'),
        ),
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Avatar URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('admin', 'Administrator'), ('developer', 'Developer')], default='user', max_length=50, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='storagecredential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='storagecredential',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='storagecredential',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Credential Name'),
        ),
        migrations.AlterField(
            model_name='storagecredential',
            name='private_key_encrypted',
            field=models.TextField(verbose_name='Private Key (Encrypted)'),
        ),
        migrations.AlterField(
            model_name='storagecredential',
            name='provider',
            field=models.CharField(choices=[('imagekit', 'ImageKit'), ('cloudinary', 'Cloudinary'), ('aws_s3', 'AWS S3'), ('google_drive', 'Google Drive')], default='imagekit', max_length=50, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='storagecredential',
            name='public_key',
            field=models.CharField(max_length=255, verbose_name='Public Key / Access Key'),
        ),
        migrations.AlterField(
            model_name='storagecredential',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='storagecredential',
            name='url_endpoint',
            field=models.URLField(max_length=500, verbose_name='URL Endpoint'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'file_type'], name='api_file_user_id_faa76f_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'folder_path'], name='api_file_user_id_fcc790_idx'),
        ),
        migrations.AddIndex(
            model_name='storagecredential',
            index=models.Index(fields=['user', 'provider'], name='api_storage_user_id_a29e83_idx'),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.file'),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
